### ISSUE TITLE
Suggestion: Multiple Sweeps to reduce noise

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#20]
Audyssey uses multiple sweeps on each loud speaker to reduce any potential noise fro measurement. 

I also found a video of a Smyth Realiser A8 being measured here that utilities the same technique: https://www.youtube.com/watch?v=cV1X8ljCRm8

The video also has good audio prompts on head placement when you eventually work on the interactive measurements via the Impulcfier itself.

For a future update I think this would be really worthwhile - my room, for example, constantly has about 35-40db noise due to being in a city.

**Comment by jaakkopasanen** [comment]
Angelo Farina, who is the inventor of exponential sine sweep measurement (ESS) technique, states in his 2007 paper "Advancements in impulse response measurements by sine sweeps" in chapter 3.5:
> The usage of averaging several impulse responses for improving the signal-to-noise ratio is a deprecated technology when working with the ESS method.

> Synchronous time averaging works only if the whole system is perfectly time-invariant. This is never the case when the system involves propagation of the sound in air, due to air movement and change of the air temperature. So, the preferred way for improving the signal to noise ratio is not to average a number of distinct measurements, but instead to perform a single, very long sweep measurement, as clearly recommended in the ISO 18233/2006 standard.

> However, in some cases the usage of long sweeps is not allowed (for example, when the method is implemented on small, portable devices equipped with little memory), and so time-synchronous averaging is the only way for getting results in a noisy environment

and 
> It can be concluded that synchronously-averaging a number of subsequent IRs obtained with the ESS method is causing unacceptable artifacts.

He also introduces a better way to average multiple sweeps which gives better results but even then the conclusion is:
> So, in practice, the employment of a number of independent sweeps can provide almost acceptable results, provided that the deconvolution and averaging of the impulse response are performed in reversed order (first averaging, then deconvolution), and in the frequency domain.

So averaged sweeps should only be used when use of single longer sweep is not possible due to hardware limitations. I can think of another case where it might be preferable to use multiple sweeps and that is when recording with high sampling rates. It's well known that using high sampling rate with phase controlled ESS (sweep is always played to the Nyquist frequency) and long sweeps can cause the tweeter to overheat. This could be alleviated by using multiple shorter sweeps to avoid long periods in the ultrasonic range which is what causes tweeter overheat. However I'm not convinced that this would be any better than running a single longer sweep with lower sampling rate.

What you hear in the Smyth Realiser video is multiple sweeps but there is only one sweep per speaker. First the subject looks at the center and there is 6 sweeps so I assume it's 5.1 system and they are also measuring the subwoofer. Then he looks to the left and to the right but I believe this is for head tracking. So I would claim that they are not averaging multiple sweeps.

There is another very effective way of improving signal to noise ratio that is used by Realiser A16 and that is tracking band-pass filter. We can calculate the frequency playing any given moment so it's possible to construct a band-pass filter which blocks all other frequencies but the currently playing one. This will also minimize the impact of impulsive noises such as dropping something on the floor. I intend to implement this tracking filter and you can follow the progress in issue #9

**Comment by rpx91** [comment]
Thanks for the detailed response - I downloaded the paper to learn more.

Makes sense that Audyssey does that because of the limited processing power on the AVR.

The band pass filter sounds like  a winner. That combined with room correction should negate the need to have to get into an optimised room for regular users.
