### ISSUE TITLE
Suggestion: Multiple Headphone Compensations / 44khz option

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#23]
This would be a nice to have:

I've got a collection of 4 headphones. I currently run compensations for all of them manually by replacing headphones.wav and re-running the command.

It'd be neat if I could just label all the headphones `headphones-USERTEXT.wav` and Impulcifer would then compensate for however many headphones were in the directory.

That way you run one command and have multiple HRIR's for the compensated headphones.

The same thing with 44.1khz for Bluetooth. Currently I take the HRIR produced by Impulcifer and re-sample in Audacity. Be neat if two HRIR's were output - one for 48khz and one for 44khz.

**Comment by jaakkopasanen** [comment]
Interesting idea, I'll think about it. Output sampling rate idea is already covered here: #15

**Comment by jaakkopasanen** [comment]
I added `--fs` parameter as per #15. So now you can output 44.1 kHz HRIRs with Impulcifer.

I've decided to keep things simple and not to implement any batch processing. You could, for example, create a sub-folder in `my_hrir` for each of your headphones, save the headphone compensation recording there and then just copy the same speaker recording files to all of the folders. You'd still need to run Impulcifer for all of the sub-folders but since there only one small part that changes in the command, this shouldn't be too much trouble. I also suspect that large part of the annoyance came from the very long processing time and since that is not an issue anymore when not plotting there should not be that big need for batch processing anymore.
