### ISSUE TITLE
How to Re-install as new from beginning I am confused with new and old instructions 

### ISSUE THREAD

**Issue by venkatesh63** [jaakkopasanen/Impulcifer#25]
@jaakkopasanen please can you explain installation and re installation as Fresh copy in impulcifer

**Comment by jaakkopasanen** [comment]
If you wish to start from scratch you can simply remove the old Impulcifer folder and follow the new installation instructions. Just ignore Python and virtualenv installation steps because you don't need to install them again to your system. Take all the other steps of the new instructions.

Keep in mind that you'll loose all the files you've added to Impulcifer folder if you remove it. So perhaps take a backup of the recording and other data files which are not included in the project Git.

**Comment by venkatesh63** [comment]
@jaakkopasanen Thanks for replying me. i seen your seen installing update i was good.
Asking again Can i get your recording's data of your Favorites one is to Speakers and one is to Headphones. Demo don't have actual measurements.

**Comment by jaakkopasanen** [comment]
I don't quite understand what are you asking for? Demo folder has `recording.wav` and `headphones.wav`. That's all there is to it. Only those two files are needed to produce HRIR files `hrir.wav` and `hesuvi.wav`.

**Comment by venkatesh63** [comment]
@jaakkopasanen ok fine when i'm using HRIR files hrir.wav and hesuvi.wav getting low sound.

**Comment by jaakkopasanen** [comment]
Click "Get suggestion" button on Connection tab. Does that give you 150 for attenuation? You would have to adjust that for each HRIR separately because all of them have different max gain. If you still are experiencing low volume after setting the attenuation automatically make sure all other volume adjustments are at max (windows, music player, headphone amp, etc...). If that don't help then you need a new headphone amp which has more power / gain.

**Comment by venkatesh63** [comment]
@jaakkopasanen  ok thanks once again.
